# Generated by Django 3.0.8 on 2020-08-27 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0002_bookmarkpost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkpost',
            unique_together={('user', 'post')},
        ),
    ]
