# Generated by Django 3.0.8 on 2020-08-25 12:31

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SR', 'Spam'), ('HR', 'Harassment'), ('VL', 'Violence'), ('EX', 'Extremism')], max_length=2, verbose_name='Report body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportListResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='task_id')),
                ('file', models.FileField(upload_to=apps.reports.models.get_upload_path, verbose_name='result_url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Report list',
                'verbose_name_plural': 'Reports lists',
                'ordering': ('created_at',),
            },
        ),
    ]
